[package]
name = "ant-1-6"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = 'triangle'
path = 'src/triangle.rs'

[dependencies]
